[package]
name = "bevy_noised"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_math = "^0.18"

[dev-dependencies]
bevy = { version = "^0.18", default-features = false, features = [
    "bevy_asset",
    "bevy_render",
    "bevy_window",
    "bevy_winit",
] }
bevy_gpu_test = "*"
